MODEL:


TRAIN:
  train_data_dir: [
           '/workspace/TPGSR/data/TextZoom/train1',
           '/workspace/TPGSR/data/TextZoom/train2',
          
  ]
  batch_size: 4
  width: 128
  height: 32
  epochs: 5000
  cuda: False
  ngpu: 1
  workers: 0
  resume: ''
  ckpt_dir: './ckpt/with_test'
  voc_type: 'all' #'digits lower upper all'
  saveInterval: 200
  displayInterval: 50 #display loss
  adadelta: False
  lr: 0.001
  adam: True
  optimizer: "Adam"
  beta1: 0.5
  manualSeed: 1234
  max_len: 100
  keep_ratio: False
  down_sample_scale: 2

  VAL:
    val_data_dir: [
             
            '/workspace/TPGSR/data/TextZoom/test/easy',
            '/workspace/TPGSR/data/TextZoom/test/medium',
            '/workspace/TPGSR/data/TextZoom/test/hard',
    ]
    n_vis: 10
    vis_dir: 'demo'
    valInterval: 200 #-1, val at the end of epoch
    rec_pretrained: '/workspace/TPGSR/pretrained/aster.pth.tar'
    moran_pretrained: '/workspace/TPGSR/pretrained/moran.pth'
    crnn_pretrained: '/workspace/TPGSR/pretrained/crnn.pth'

TEST:
  checkpoint: ''
  test_data_dir: [
  ]

CONVERT:
  image_dir:
  lmdb_dir:
  n_convert: 10
